// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Vulnerabilities Vulnerabilities of the scanned SBOM
//
// swagger:model Vulnerabilities
type Vulnerabilities struct {

	// vulnerabilities
	// Format: byte
	Vulnerabilities strfmt.Base64 `json:"vulnerabilities,omitempty"`
}

// Validate validates this vulnerabilities
func (m *Vulnerabilities) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vulnerabilities based on context it is used
func (m *Vulnerabilities) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Vulnerabilities) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Vulnerabilities) UnmarshalBinary(b []byte) error {
	var res Vulnerabilities
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
