// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Grype server",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/scanSBOM": {
      "post": {
        "summary": "Scan SBOM (Software Bill Of Materials) for vulnerabilities",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SBOM"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful scan result of the provided SBOM",
            "schema": {
              "$ref": "#/definitions/Vulnerabilities"
            }
          },
          "default": {
            "$ref": "#/responses/UnknownError"
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "description": "An object that is returned in all cases of failures.",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "SBOM": {
      "description": "Software Bill Of Materials to scan for vulnerabilities",
      "type": "object",
      "properties": {
        "sbom": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "Vulnerabilities": {
      "description": "Vulnerabilities of the scanned SBOM",
      "type": "object",
      "properties": {
        "vulnerabilities": {
          "type": "string",
          "format": "byte"
        }
      }
    }
  },
  "responses": {
    "UnknownError": {
      "description": "unknown error",
      "schema": {
        "$ref": "#/definitions/ApiResponse"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Grype server",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/scanSBOM": {
      "post": {
        "summary": "Scan SBOM (Software Bill Of Materials) for vulnerabilities",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SBOM"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful scan result of the provided SBOM",
            "schema": {
              "$ref": "#/definitions/Vulnerabilities"
            }
          },
          "default": {
            "description": "unknown error",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "description": "An object that is returned in all cases of failures.",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "SBOM": {
      "description": "Software Bill Of Materials to scan for vulnerabilities",
      "type": "object",
      "properties": {
        "sbom": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "Vulnerabilities": {
      "description": "Vulnerabilities of the scanned SBOM",
      "type": "object",
      "properties": {
        "vulnerabilities": {
          "type": "string",
          "format": "byte"
        }
      }
    }
  },
  "responses": {
    "UnknownError": {
      "description": "unknown error",
      "schema": {
        "$ref": "#/definitions/ApiResponse"
      }
    }
  }
}`))
}
