// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PostScanSBOM(params *PostScanSBOMParams, opts ...ClientOption) (*PostScanSBOMOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  PostScanSBOM scans s b o m software bill of materials for vulnerabilities
*/
func (a *Client) PostScanSBOM(params *PostScanSBOMParams, opts ...ClientOption) (*PostScanSBOMOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostScanSBOMParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostScanSBOM",
		Method:             "POST",
		PathPattern:        "/scanSBOM",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostScanSBOMReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostScanSBOMOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostScanSBOMDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
