// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Portshift/grype-server/api/server/models"
)

// PostScanSBOMOKCode is the HTTP code returned for type PostScanSBOMOK
const PostScanSBOMOKCode int = 200

/*PostScanSBOMOK status reported successfully

swagger:response postScanSBOMOK
*/
type PostScanSBOMOK struct {

	/*
	  In: Body
	*/
	Payload *models.Vulnerabilities `json:"body,omitempty"`
}

// NewPostScanSBOMOK creates PostScanSBOMOK with default headers values
func NewPostScanSBOMOK() *PostScanSBOMOK {

	return &PostScanSBOMOK{}
}

// WithPayload adds the payload to the post scan s b o m o k response
func (o *PostScanSBOMOK) WithPayload(payload *models.Vulnerabilities) *PostScanSBOMOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post scan s b o m o k response
func (o *PostScanSBOMOK) SetPayload(payload *models.Vulnerabilities) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostScanSBOMOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostScanSBOMDefault unknown error

swagger:response postScanSBOMDefault
*/
type PostScanSBOMDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewPostScanSBOMDefault creates PostScanSBOMDefault with default headers values
func NewPostScanSBOMDefault(code int) *PostScanSBOMDefault {
	if code <= 0 {
		code = 500
	}

	return &PostScanSBOMDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post scan s b o m default response
func (o *PostScanSBOMDefault) WithStatusCode(code int) *PostScanSBOMDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post scan s b o m default response
func (o *PostScanSBOMDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post scan s b o m default response
func (o *PostScanSBOMDefault) WithPayload(payload *models.APIResponse) *PostScanSBOMDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post scan s b o m default response
func (o *PostScanSBOMDefault) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostScanSBOMDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
