name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

permissions: read-all

jobs:
  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yaml
    with:
      publish: true
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
